var subscribedEvents ={
	doc:
		{		
		email:{	W2:{type:Boolean,default: true},
				taxes:{type:Boolean,default: true},
				payStub:{type:Boolean,default: true},
				bankStatements:{type:Boolean,default: true},
				prequal:{type:Boolean,default: true},
				driversLicense:{type:Boolean,default: true},
				socialSecurityCard:{type:Boolean,default: true},
				application:{type:Boolean,default: true},
				submissionForm:{type:Boolean,default: true},
				signed:{type:Boolean,default: true},
				preApproved:{type:Boolean,default: true},
				prequalAgent:{type:Boolean,default: true},
				showHouses:{type:Boolean,default: true},
				madeOffer:{type:Boolean,default: true},
				offerStatus:{type:Boolean,default: true},
				appraisal:{type:Boolean,default: true},
				escrow:{type:Boolean,default: true},
				closed:{type:Boolean,default: true},
				EMD:{type:Boolean,default: true},
				prelim:{type:Boolean,default: true},
				escrowInstruction:{type:Boolean,default: true},
				reDisclosures:{type:Boolean,default: true},
				homeInspections:{type:Boolean,default: true},
				NTP:{type:Boolean,default: true},
				FWT:{type:Boolean,default: true},
				credit:{type:Boolean,default: true},
				updatedDocs:{type:Boolean,default: true},
				conditions:{type:Boolean,default: true},
				subOfLoan:{type:Boolean,default: true},
				approved:{type:Boolean,default: true},
				priorToDocs:{type:Boolean,default: true},
				PTFconditions:{type:Boolean,default: true},
				funding:{type:Boolean,default: true},
				}
		,text:{	W2:{type:Boolean,default: false},
				taxes:{type:Boolean,default: false},
				payStub:{type:Boolean,default: false},
				bankStatements:{type:Boolean,default: false},
				prequal:{type:Boolean,default: false},
				driversLicense:{type:Boolean,default: false},
				socialSecurityCard:{type:Boolean,default: false},
				application:{type:Boolean,default: false},
				submissionForm:{type:Boolean,default: false},
				signed:{type:Boolean,default: false},
				preApproved:{type:Boolean,default: false},
				prequalAgent:{type:Boolean,default: false},
				showHouses:{type:Boolean,default: false},
				madeOffer:{type:Boolean,default: false},
				offerStatus:{type:Boolean,default: false},
				appraisal:{type:Boolean,default: false},
				escrow:{type:Boolean,default: false},
				closed:{type:Boolean,default: false},
				EMD:{type:Boolean,default: false},
				prelim:{type:Boolean,default: false},
				escrowInstruction:{type:Boolean,default: false},
				reDisclosures:{type:Boolean,default: false},
				homeInspections:{type:Boolean,default: false},
				NTP:{type:Boolean,default: false},
				FWT:{type:Boolean,default: false},
				credit:{type:Boolean,default: false},
				updatedDocs:{type:Boolean,default: false},
				conditions:{type:Boolean,default: false},
				subOfLoan:{type:Boolean,default: false},
				approved:{type:Boolean,default: false},
				priorToDocs:{type:Boolean,default: false},
				PTFconditions:{type:Boolean,default: false},
				funding:{type:Boolean,default: false},
				}
		},
	accessTo:{
		email:{type:Boolean,default:true}
		,text:{type:Boolean,default:false}
		} 
	};

module.exports = subscribedEvents;
